[package]
name = "api_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
# Version-locked to not make the CI go out of date
bindgen = "=0.70.1"
# Force a higher version to fix https://github.com/rust-lang/regex/issues/770 in MSRV
regex-syntax = "0.6.26"
